# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "5bf173e80edc15dc5b1620e0d0936bfd"
application_url = "https://yours-farms-mask-cdna.trycloudflare.com"
embedded = true
name = "Busy Buddy"
handle = "busy-buddy-3"

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quickstart-53ae8bcc.myshopify.com"

[webhooks]
api_version = "2024-10"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [
  "https://yours-farms-mask-cdna.trycloudflare.com/auth/callback",
  "https://yours-farms-mask-cdna.trycloudflare.com/auth/shopify/callback",
  "https://yours-farms-mask-cdna.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
