# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "66741fd2a46bacd291b55be34ac42d9d"
name = "BusyBuddy"
handle = "busybuddy-6"
application_url = "https://animated-gbp-mistakes-tray.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
dev_store_url = "quickstart-d7cce324.myshopify.com"
automatically_update_urls_on_dev = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [
  "https://animated-gbp-mistakes-tray.trycloudflare.com/auth/callback",
  "https://animated-gbp-mistakes-tray.trycloudflare.com/auth/shopify/callback",
  "https://animated-gbp-mistakes-tray.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-10"

[pos]
embedded = false
