# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "3420c14f9c2a7ba0b6bbc3d1e0388be9"
name = "BusyBuddy"
handle = "busybuddy-19"
application_url = "https://getbusybuddy.com"
embedded = true

[build]
include_config_on_deploy = true
dev_store_url = "quickstart-f05d22ad.myshopify.com"
automatically_update_urls_on_dev = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_script_tags,write_script_tags,read_themes,read_orders,read_customers,read_discounts,write_discounts,read_shipping,read_products,write_products"

[auth]
redirect_urls = [
  "https://getbusybuddy.com/auth/callback",
  "https://getbusybuddy.com/auth/shopify/callback",
  "https://getbusybuddy.com/api/auth/callback"
]

[webhooks]
api_version = "2024-10"

[[webhooks.subscriptions]]
topics = [ "app/uninstalled" ]
uri = "/webhooks"
compliance_topics = [ "customers/data_request", "customers/redact", "shop/redact" ]

[pos]
embedded = false
