# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "5ece593ddde7baa448fd292657ed2b87"
name = "BusyBuddy"
handle = "busybuddy-59"
application_url = "https://paperback-apt-prevention-day.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
dev_store_url = "quickstart-f05d22ad.myshopify.com"
automatically_update_urls_on_dev = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_script_tags,write_script_tags,read_themes,read_orders,read_customers,read_discounts,write_discounts,read_shipping,read_products,write_products"


[auth]
redirect_urls = [
  "https://paperback-apt-prevention-day.trycloudflare.com/auth/callback",
  "https://paperback-apt-prevention-day.trycloudflare.com/auth/shopify/callback",
  "https://paperback-apt-prevention-day.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2025-01"

[pos]
embedded = false
