# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "25ea09b1b5523b80bf80b05ab18131da"
application_url = "https://promotes-blame-defensive-sir.trycloudflare.com"
embedded = true
name = "BusyBuddy-Development"
handle = "busybuddy-development-1"

[build]
include_config_on_deploy = true
dev_store_url = "quickstart-f05d22ad.myshopify.com"

[webhooks]
api_version = "2025-01"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,read_discounts,read_orders,read_products,read_script_tags,read_shipping,read_themes,write_discounts,write_products,write_script_tags"

[auth]
redirect_urls = [
  "https://promotes-blame-defensive-sir.trycloudflare.com/auth/callback",
  "https://promotes-blame-defensive-sir.trycloudflare.com/auth/shopify/callback",
  "https://promotes-blame-defensive-sir.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
