# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "4456f7074859b6f6ab901d539c7341e5"
name = "Busy Buddy"
handle = "busy-buddy-1"
application_url = "https://diy-keeping-strand-perl.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
dev_store_url = "quickstart-5ffb74f8.myshopify.com"
automatically_update_urls_on_dev = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [
  "https://diy-keeping-strand-perl.trycloudflare.com/auth/callback",
  "https://diy-keeping-strand-perl.trycloudflare.com/auth/shopify/callback",
  "https://diy-keeping-strand-perl.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-10"

[pos]
embedded = false
