# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "958abe7d38c5db83dc82e0ac551d1409"
name = "BusyBuddy"
handle = "busybuddy-4"
application_url = "https://interact-brief-graduation-toronto.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
dev_store_url = "quickstart-f05d22ad.myshopify.com"
automatically_update_urls_on_dev = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [
  "https://interact-brief-graduation-toronto.trycloudflare.com/auth/callback",
  "https://interact-brief-graduation-toronto.trycloudflare.com/auth/shopify/callback",
  "https://interact-brief-graduation-toronto.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-10"

[pos]
embedded = false
