# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "8568ff3809c7d25c65a43451869b7437"
name = "BusyBuddy"
handle = "busybuddy-10"
application_url = "https://poultry-gordon-loading-thanksgiving.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
dev_store_url = "budybuddystore.myshopify.com"
automatically_update_urls_on_dev = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [
  "https://poultry-gordon-loading-thanksgiving.trycloudflare.com/auth/callback",
  "https://poultry-gordon-loading-thanksgiving.trycloudflare.com/auth/shopify/callback",
  "https://poultry-gordon-loading-thanksgiving.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-10"

[pos]
embedded = false
