# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "0c01584bc86b3e65af0afb488aec7964"
name = "BusyBuddy"
handle = "busybuddy-61"
application_url = "https://championship-bigger-write-knife.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
dev_store_url = "quickstart-f05d22ad.myshopify.com"
automatically_update_urls_on_dev = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,read_discounts,read_orders,read_products,read_publications,read_script_tags,read_shipping,read_themes,write_discounts,write_products,write_publications,write_script_tags"

[auth]
redirect_urls = [
  "https://championship-bigger-write-knife.trycloudflare.com/auth/callback",
  "https://championship-bigger-write-knife.trycloudflare.com/auth/shopify/callback",
  "https://championship-bigger-write-knife.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2025-01"

[pos]
embedded = false
