# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "e839382a6178a1ba6e9b7ae24487c173"
name = "Busy Buddy"
handle = "busy-buddy-1"
application_url = "https://forest-cc-promoting-ni.trycloudflare.com"
embedded = true
name = "Busy Buddy"
handle = "busy-buddy-3"

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quickstart-53ae8bcc.myshopify.com"

[webhooks]
api_version = "2024-10"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [
  "https://forest-cc-promoting-ni.trycloudflare.com/auth/callback",
  "https://forest-cc-promoting-ni.trycloudflare.com/auth/shopify/callback",
  "https://forest-cc-promoting-ni.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
