# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "49ec0d3907fd1c87c4dc29953cc24fc0"
name = "BusyBuddy"
handle = "busybuddy-12"
application_url = "https://midwest-accessibility-leonard-counted.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
dev_store_url = "quickstart-f05d22ad.myshopify.com"
automatically_update_urls_on_dev = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_script_tags,write_script_tags"

[auth]
redirect_urls = [
  "https://midwest-accessibility-leonard-counted.trycloudflare.com/auth/callback",
  "https://midwest-accessibility-leonard-counted.trycloudflare.com/auth/shopify/callback",
  "https://midwest-accessibility-leonard-counted.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-10"

[pos]
embedded = false
