# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "f917087e0914103830db8dd72df385b0"
name = "BusyBuddy"
handle = "busybuddy-41"
application_url = "https://jokes-furnishings-poison-blonde.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
dev_store_url = "quickstart-d7cce324.myshopify.com"
automatically_update_urls_on_dev = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_script_tags,write_script_tags,read_themes,read_orders,read_customers,read_discounts,write_discounts,read_shipping"

[auth]
redirect_urls = [
  "https://jokes-furnishings-poison-blonde.trycloudflare.com/auth/callback",
  "https://jokes-furnishings-poison-blonde.trycloudflare.com/auth/shopify/callback",
  "https://jokes-furnishings-poison-blonde.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-10"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  compliance_topics = [ "customers/redact", "customers/data_request", "shop/redact" ]
  uri = "/webhooks"

[pos]
embedded = false
